Repository saleemhamo/traffic-light-system, pull requests merged in 2024-04, with the labels that each got.

#63 Enhance timer / Change logs -> async
  CMakeLists.txt
  include/main/MainSystem.h
  include/utils/Logger.h
  include/utils/Timer.cpp
  include/utils/Timer.h
  src/main.cpp
  src/main/MainSystem.cpp
  src/utils/Logger.cpp
  tests/TimerTest.cpp
  tests/hardware_tests/actuators/Buzzer_test.cpp
  tests/hardware_tests/actuators/LED_test.cpp
  tests/hardware_tests/sensors/Ultrasonic_test.cpp
  web/logs.html
Labels: enhancement

#67 [HW Testing Needed] Fix debouncing issue
  include/sensors/UltrasonicSensor.h
  src/main/CheckingSystem.cpp
  src/sensors/UltrasonicSensor.cpp
  tests/hardware_tests/sensors/Ultrasonic_test.cpp
Labels: bug

#79 Unit tests Phase 2
  CMakeLists.txt
  include/main/CheckingSystem.h
  include/main/WarningSystem.h
  include/pigpio_stub.h
  include/sensors/PushButton.h
  include/utils/FirestoreLogger.h
  src/main.cpp
  src/main/CheckingSystem.cpp
  src/main/MainSystem.cpp
  src/main/WarningSystem.cpp
  src/pigpio_stub.cpp
  src/sensors/PushButton.cpp
  src/utils/FirestoreLogger.cpp
  tests/hardware_tests/sensors/PushButton_test.cpp
  tests/logic_tests/main/CarsTrafficLightSystem_test.cpp
  tests/logic_tests/main/CheckingSystem_test.cpp
  tests/logic_tests/main/PedestriansTrafficLightSystem_test.cpp
  tests/logic_tests/main/WarningSystem_test.cpp
  tests/logic_tests/models/TrafficLight_test.cpp
  tests/logic_tests/utils/FirestoreLogger_test.cpp
  tests/logic_tests/utils/Logger_test.cpp
  tests/logic_tests/utils/Timer_test.cpp
Labels: enhancement, question

#84 Final HW testing / demo
  CMakeLists.txt
  Doxyfile
  include/main/CheckingSystem.h
  include/main/WarningSystem.h
  include/pigpio_stub.h
  include/sensors/PushButton.h
  include/utils/FirestoreLogger.h
  src/main.cpp
  src/main/CheckingSystem.cpp
  src/main/MainSystem.cpp
  src/main/WarningSystem.cpp
  src/pigpio_stub.cpp
  src/sensors/PushButton.cpp
  src/utils/FirestoreLogger.cpp
  tests/hardware_tests/sensors/PushButton_test.cpp
  tests/logic_tests/main/CarsTrafficLightSystem_test.cpp
  tests/logic_tests/main/CheckingSystem_test.cpp
  tests/logic_tests/main/PedestriansTrafficLightSystem_test.cpp
  tests/logic_tests/main/WarningSystem_test.cpp
  tests/logic_tests/models/TrafficLight_test.cpp
  tests/logic_tests/utils/FirestoreLogger_test.cpp
  tests/logic_tests/utils/Logger_test.cpp
  tests/logic_tests/utils/Timer_test.cpp
Labels: enhancement
